package de.xbank.onlinebanking;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2016-05-02T17:51:04.938+02:00
 * Generated source version: 3.1.4
 * 
 */
@WebServiceClient(name = "XbankOnlineIntegrationService", 
                  wsdlLocation = "http://localhost:8080/xbank/XbankOnlineIntegration?wsdl",
                  targetNamespace = "http://onlinebanking.xbank.de/") 
public class XbankOnlineIntegrationService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://onlinebanking.xbank.de/", "XbankOnlineIntegrationService");
    public final static QName XbankOnlineIntegrationPort = new QName("http://onlinebanking.xbank.de/", "XbankOnlineIntegrationPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/xbank/XbankOnlineIntegration?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(XbankOnlineIntegrationService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/xbank/XbankOnlineIntegration?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public XbankOnlineIntegrationService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public XbankOnlineIntegrationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public XbankOnlineIntegrationService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public XbankOnlineIntegrationService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public XbankOnlineIntegrationService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public XbankOnlineIntegrationService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns XbankOnlineIntegration
     */
    @WebEndpoint(name = "XbankOnlineIntegrationPort")
    public XbankOnlineIntegration getXbankOnlineIntegrationPort() {
        return super.getPort(XbankOnlineIntegrationPort, XbankOnlineIntegration.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns XbankOnlineIntegration
     */
    @WebEndpoint(name = "XbankOnlineIntegrationPort")
    public XbankOnlineIntegration getXbankOnlineIntegrationPort(WebServiceFeature... features) {
        return super.getPort(XbankOnlineIntegrationPort, XbankOnlineIntegration.class, features);
    }

}
