package de.xbank.onlinebanking;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2016-05-02T17:51:04.891+02:00
 * Generated source version: 3.1.4
 * 
 */
@WebService(targetNamespace = "http://onlinebanking.xbank.de/", name = "XbankOnlineIntegration")
@XmlSeeAlso({ObjectFactory.class})
public interface XbankOnlineIntegration {

    @WebMethod
    @RequestWrapper(localName = "login", targetNamespace = "http://onlinebanking.xbank.de/", className = "de.xbank.onlinebanking.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://onlinebanking.xbank.de/", className = "de.xbank.onlinebanking.LoginResponse")
    @WebResult(name = "return", targetNamespace = "")
    public de.xbank.onlinebanking.UserLoginResponse login(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @RequestWrapper(localName = "getMyAccounts", targetNamespace = "http://onlinebanking.xbank.de/", className = "de.xbank.onlinebanking.GetMyAccounts")
    @ResponseWrapper(localName = "getMyAccountsResponse", targetNamespace = "http://onlinebanking.xbank.de/", className = "de.xbank.onlinebanking.GetMyAccountsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public de.xbank.onlinebanking.AccountListResponse getMyAccounts(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebMethod
    @RequestWrapper(localName = "logout", targetNamespace = "http://onlinebanking.xbank.de/", className = "de.xbank.onlinebanking.Logout")
    @ResponseWrapper(localName = "logoutResponse", targetNamespace = "http://onlinebanking.xbank.de/", className = "de.xbank.onlinebanking.LogoutResponse")
    @WebResult(name = "return", targetNamespace = "")
    public de.xbank.onlinebanking.ReturncodeResponse logout(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getBalance", targetNamespace = "http://onlinebanking.xbank.de/", className = "de.xbank.onlinebanking.GetBalance")
    @ResponseWrapper(localName = "getBalanceResponse", targetNamespace = "http://onlinebanking.xbank.de/", className = "de.xbank.onlinebanking.GetBalanceResponse")
    @WebResult(name = "return", targetNamespace = "")
    public de.xbank.onlinebanking.AccountBalanceResponse getBalance(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );

    @WebMethod
    @RequestWrapper(localName = "transfer", targetNamespace = "http://onlinebanking.xbank.de/", className = "de.xbank.onlinebanking.Transfer")
    @ResponseWrapper(localName = "transferResponse", targetNamespace = "http://onlinebanking.xbank.de/", className = "de.xbank.onlinebanking.TransferResponse")
    @WebResult(name = "return", targetNamespace = "")
    public de.xbank.onlinebanking.TransferMoneyResponse transfer(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.math.BigDecimal arg3
    );
}
